### ISSUE TITLE
New API in latest SII Decrypt

### ISSUE THREAD

**Issue by ghost** [CaptainFlint/wcx_sii_decrypt#1]
I have changed most of the exported functions in sii_decrypt.dll. Specificaly, the return values have been changed (parameters and general behaviour is the same). Also, there are some new functions, but that is not important here.
Can you please update your plugin so it accounts for the changes?

**Comment by CaptainFlint** [comment]
OK, will do.

**Comment by CaptainFlint** [comment]
The code was adapted to the latest API, but the new version cannot be released until the upstream issue https://github.com/ncs-sniper/SII_Decrypt/issues/5 is fixed.

**Comment by CaptainFlint** [comment]
Fixed and released.
